# 1. Build stage
FROM maven:3.9.8-eclipse-temurin-21 AS builder
WORKDIR /app

COPY pom.xml mvnw ./
RUN chmod +x mvnw
COPY .mvn/ .mvn
COPY src/ src/
RUN ./mvnw clean package -DskipTests

# 2. Runtime stage
FROM eclipse-temurin:21-jre AS runtime
WORKDIR /app
# Copy DB
COPY db.db db.db
# Copy JAR
COPY --from=builder /app/target/*.jar app.jar

# 3. Declare build-time args (to read Railway vars during build if needed)
# Build-time args
ARG SPRING_APPLICATION_NAME
ARG SPRING_MVC_DISPATCH_OPTIONS_REQUEST
ARG SECURE_COOKIE
ARG FRONTEND_ADDRESS
ARG SPRINGDOC_SWAGGER_UI_AUTHORIZATION_BEARER_FORMAT
ARG SPRINGDOC_SWAGGER_UI_REQUEST_REDIRECT_ENABLED
ARG SPRINGDOC_SWAGGER_UI_PERSIST_AUTHORIZE
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_DRIVER_CLASS_NAME
ARG SPRING_DATASOURCE_HIKARI_CONNECTION_TEST_QUERY
ARG SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
ARG JWT_SECRET
ARG JWT_ACCESS_EXPIRATION
ARG JWT_REFRESH_EXPIRATION

# Runtime ENV
ENV SPRING_APPLICATION_NAME=$SPRING_APPLICATION_NAME \
    SPRING_MVC_DISPATCH_OPTIONS_REQUEST=$SPRING_MVC_DISPATCH_OPTIONS_REQUEST \
    SECURE_COOKIE=$SECURE_COOKIE \
    FRONTEND_ADDRESS=$FRONTEND_ADDRESS \
    SPRINGDOC_SWAGGER_UI_AUTHORIZATION_BEARER_FORMAT=$SPRINGDOC_SWAGGER_UI_AUTHORIZATION_BEARER_FORMAT \
    SPRINGDOC_SWAGGER_UI_REQUEST_REDIRECT_ENABLED=$SPRINGDOC_SWAGGER_UI_REQUEST_REDIRECT_ENABLED \
    SPRINGDOC_SWAGGER_UI_PERSIST_AUTHORIZE=$SPRINGDOC_SWAGGER_UI_PERSIST_AUTHORIZE \
    SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL \
    SPRING_DATASOURCE_DRIVER_CLASS_NAME=$SPRING_DATASOURCE_DRIVER_CLASS_NAME \
    SPRING_DATASOURCE_HIKARI_CONNECTION_TEST_QUERY=$SPRING_DATASOURCE_HIKARI_CONNECTION_TEST_QUERY \
    SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=$SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT \
    JWT_SECRET=$JWT_SECRET \
    JWT_ACCESS_EXPIRATION=$JWT_ACCESS_EXPIRATION \
    JWT_REFRESH_EXPIRATION=$JWT_REFRESH_EXPIRATION

# Hardcoded port example
ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java -Dserver.port=$PORT -jar app.jar"]


# 5. Specify port
ENV PORT=8080
EXPOSE 8080

# 6. Launch using shell form (so $PORT expands)
ENTRYPOINT ["sh", "-c", "java -Dserver.port=$PORT -jar app.jar"]
